# Generated by Django 5.1.4 on 2025-02-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDSApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='available',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='price',
        ),
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='room_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
