# Generated by Django 5.1.4 on 2025-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDSApp', '0002_remove_apartment_available_remove_apartment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
