# Generated by Django 5.1.4 on 2025-02-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDSApp', '0007_alter_apartment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/'),
        ),
    ]
