# Generated by Django 5.1.4 on 2025-02-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDSApp', '0008_building_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
